analyzer:
  # errors:
  #   avoid_print: ignore
  #   dangling_library_doc_comments: ignore
  #   depend_on_referenced_packages: ignore
  #   deprecated_member_use: ignore
  #   empty_catches: ignore
  #   unused_local_variable: ignore
  #   use_build_context_synchronously: ignore

include: package:flutter_lints/flutter.yaml
