// <auto-generated />
using System;
using HeThongChungCu.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeThongChungCu.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326063429_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.BangGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DichVuId")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiDinhGiaId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayApDung")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenBangGia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("BangGia", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.BangGiaLuyTien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BangGiaId")
                        .HasColumnType("int");

                    b.Property<double?>("DenMuc")
                        .HasColumnType("float");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("TuMuc")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BangGiaId");

                    b.ToTable("BangGiaLuyTien", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.CanHo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("DienTich")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiCanHoId")
                        .HasColumnType("int");

                    b.Property<string>("MaCanHo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("SoPhongNgu")
                        .HasColumnType("int");

                    b.Property<int>("SoPhongTam")
                        .HasColumnType("int");

                    b.Property<int>("TangId")
                        .HasColumnType("int");

                    b.Property<string>("TenCanHo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TinhTrangCanHoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaCanHo")
                        .IsUnique();

                    b.HasIndex("TangId");

                    b.ToTable("CanHo", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.CauHinhLai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("LaiSuatThang")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaCauHinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayApDung")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguongQuaHanNang")
                        .HasColumnType("int");

                    b.Property<int>("NguongQuaHanNhe")
                        .HasColumnType("int");

                    b.Property<int>("SoNgayChoPhep")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaCauHinh")
                        .IsUnique();

                    b.ToTable("CauHinhLai", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.ChiSoTieuThu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CanHoId")
                        .HasColumnType("int");

                    b.Property<double>("ChiSoCu")
                        .HasColumnType("float");

                    b.Property<double>("ChiSoMoi")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DichVuId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLock")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayChot")
                        .HasColumnType("datetime2");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CanHoId");

                    b.HasIndex("DichVuId");

                    b.ToTable("ChiSoTieuThu", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.ChiTietHoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("ChiSoCuoi")
                        .HasColumnType("float");

                    b.Property<double?>("ChiSoDau")
                        .HasColumnType("float");

                    b.Property<int>("DichVuId")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoaDonId")
                        .HasColumnType("int");

                    b.Property<int>("LoaiChiTietId")
                        .HasColumnType("int");

                    b.Property<double>("SoLuong")
                        .HasColumnType("float");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonId");

                    b.ToTable("ChiTietHoaDon", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.DangKyDichVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CanHoId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DichVuId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("CanHoId");

                    b.HasIndex("DichVuId");

                    b.ToTable("DangKyDichVu", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.DichVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaDichVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("MaDichVu")
                        .IsUnique();

                    b.ToTable("DichVu", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.HoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CanHoId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HanThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiHoaDonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaHoaDon")
                        .IsUnique();

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.LaiChamTra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HoaDonId")
                        .HasColumnType("int");

                    b.Property<decimal>("LaiSuat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NgayTinh")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoNgayCham")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienGoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoTienLai")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonId");

                    b.ToTable("LaiChamTra", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CCCD")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GioiTinhId")
                        .HasColumnType("int");

                    b.Property<string>("Ho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CCCD")
                        .IsUnique()
                        .HasFilter("[CCCD] IS NOT NULL");

                    b.HasIndex("SoDienThoai")
                        .IsUnique()
                        .HasFilter("[SoDienThoai] IS NOT NULL");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.PhanQuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("TaiKhoanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("PhanQuyen", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.PhuongTien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BienSo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CanHoId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiPhuongTienId")
                        .HasColumnType("int");

                    b.Property<string>("MauXe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("TenPhuongTien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThaiPhuongTienId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BienSo")
                        .IsUnique();

                    b.HasIndex("CanHoId");

                    b.ToTable("PhuongTien", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.QuanHeCuTru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CanHoId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiQuanHeCuTruId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiCuTruId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("CanHoId", "NguoiDungId")
                        .IsUnique()
                        .HasFilter("[TrangThaiCuTruId] = 1");

                    b.ToTable("QuanHeCuTru", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnhDaiDienId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AnhDaiDienId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NguoiDungId")
                        .IsUnique()
                        .HasFilter("[NguoiDungId] IS NOT NULL");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.TaiLieuNguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LoaiGiayToId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayPhatHanh")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("SoGiayTo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("TaiLieuNguoiDung", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.Tang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiTangId")
                        .HasColumnType("int");

                    b.Property<string>("MaTang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("TenTang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ToaNhaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ToaNhaId", "MaTang")
                        .IsUnique();

                    b.ToTable("Tang", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.TepTaiLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TepTaiLieu", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.ThanhToan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HoaDonId")
                        .HasColumnType("int");

                    b.Property<string>("MaGiaoDich")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PhuongThucThanhToanId")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonId");

                    b.ToTable("ThanhToan", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.ThePhuongTien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("MaThe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhuongTienId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaThe")
                        .IsUnique();

                    b.HasIndex("PhuongTienId");

                    b.ToTable("ThePhuongTien", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.ToaNha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaToaNha")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("TenToaNha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThaiToaNhaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaToaNha")
                        .IsUnique();

                    b.ToTable("ToaNha", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.Tokens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ExpiresDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<int?>("ReasonRevoked")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TaiKhoanId")
                        .HasColumnType("int");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TokenType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("Token", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.YeuCauCuTru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CanHoId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiYeuCauId")
                        .HasColumnType("int");

                    b.Property<string>("LyDo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiXuLyId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("QuanHeCuTruId")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiId")
                        .HasColumnType("int");

                    b.Property<int?>("YeuCauGioiTinhId")
                        .HasColumnType("int");

                    b.Property<string>("YeuCauHo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("YeuCauLoaiQuanHeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("YeuCauNgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("YeuCauSoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("YeuCauTen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CanHoId");

                    b.HasIndex("QuanHeCuTruId");

                    b.ToTable("YeuCauCuTru", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.YeuCauTaiLieuCuTru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LoaiGiayToId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayPhatHanh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoGiayTo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("YeuCauCuTruId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("YeuCauCuTruId");

                    b.ToTable("YeuCauTaiLieuCuTru", (string)null);
                });

            modelBuilder.Entity("TaiLieuNguoiDungTepTaiLieu", b =>
                {
                    b.Property<int>("FilesId")
                        .HasColumnType("int");

                    b.Property<int>("TaiLieuNguoiDungId")
                        .HasColumnType("int");

                    b.HasKey("FilesId", "TaiLieuNguoiDungId");

                    b.HasIndex("TaiLieuNguoiDungId");

                    b.ToTable("TepTaiLieuNguoiDung", (string)null);
                });

            modelBuilder.Entity("TepTaiLieuYeuCauTaiLieuCuTru", b =>
                {
                    b.Property<int>("FilesId")
                        .HasColumnType("int");

                    b.Property<int>("YeuCauTaiLieuCuTruId")
                        .HasColumnType("int");

                    b.HasKey("FilesId", "YeuCauTaiLieuCuTruId");

                    b.HasIndex("YeuCauTaiLieuCuTruId");

                    b.ToTable("TepYeuCauTaiLieuCuTru", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.BangGiaLuyTien", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.BangGia", null)
                        .WithMany("BangGiaLuyTiens")
                        .HasForeignKey("BangGiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.CanHo", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.Tang", null)
                        .WithMany()
                        .HasForeignKey("TangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.ChiSoTieuThu", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.CanHo", null)
                        .WithMany()
                        .HasForeignKey("CanHoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeThongChungCu.Domain.Entities.DichVu", null)
                        .WithMany()
                        .HasForeignKey("DichVuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.ChiTietHoaDon", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.HoaDon", null)
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.DangKyDichVu", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.CanHo", null)
                        .WithMany()
                        .HasForeignKey("CanHoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeThongChungCu.Domain.Entities.DichVu", null)
                        .WithMany()
                        .HasForeignKey("DichVuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.LaiChamTra", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.HoaDon", null)
                        .WithMany("LaiChamTras")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.PhanQuyen", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany("PhanQuyens")
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.PhuongTien", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.CanHo", null)
                        .WithMany()
                        .HasForeignKey("CanHoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.QuanHeCuTru", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.CanHo", null)
                        .WithMany()
                        .HasForeignKey("CanHoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongChungCu.Domain.Entities.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.TaiKhoan", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.TepTaiLieu", "AnhDaiDien")
                        .WithMany()
                        .HasForeignKey("AnhDaiDienId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HeThongChungCu.Domain.Entities.NguoiDung", null)
                        .WithOne()
                        .HasForeignKey("HeThongChungCu.Domain.Entities.TaiKhoan", "NguoiDungId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AnhDaiDien");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.TaiLieuNguoiDung", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("TaiLieu")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.Tang", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.ToaNha", "ToaNha")
                        .WithMany("Tangs")
                        .HasForeignKey("ToaNhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToaNha");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.ThanhToan", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.HoaDon", null)
                        .WithMany("ThanhToans")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.ThePhuongTien", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.PhuongTien", null)
                        .WithMany("ThePhuongTiens")
                        .HasForeignKey("PhuongTienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.Tokens", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany("Tokens")
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.YeuCauCuTru", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.CanHo", "CanHo")
                        .WithMany()
                        .HasForeignKey("CanHoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeThongChungCu.Domain.Entities.QuanHeCuTru", "QuanHeCuTru")
                        .WithMany()
                        .HasForeignKey("QuanHeCuTruId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CanHo");

                    b.Navigation("QuanHeCuTru");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.YeuCauTaiLieuCuTru", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.YeuCauCuTru", "YeuCauCuTru")
                        .WithMany("Documents")
                        .HasForeignKey("YeuCauCuTruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YeuCauCuTru");
                });

            modelBuilder.Entity("TaiLieuNguoiDungTepTaiLieu", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.TepTaiLieu", null)
                        .WithMany()
                        .HasForeignKey("FilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongChungCu.Domain.Entities.TaiLieuNguoiDung", null)
                        .WithMany()
                        .HasForeignKey("TaiLieuNguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TepTaiLieuYeuCauTaiLieuCuTru", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.TepTaiLieu", null)
                        .WithMany()
                        .HasForeignKey("FilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongChungCu.Domain.Entities.YeuCauTaiLieuCuTru", null)
                        .WithMany()
                        .HasForeignKey("YeuCauTaiLieuCuTruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.BangGia", b =>
                {
                    b.Navigation("BangGiaLuyTiens");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("LaiChamTras");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.NguoiDung", b =>
                {
                    b.Navigation("TaiLieu");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.PhuongTien", b =>
                {
                    b.Navigation("ThePhuongTiens");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.TaiKhoan", b =>
                {
                    b.Navigation("PhanQuyens");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.ToaNha", b =>
                {
                    b.Navigation("Tangs");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.YeuCauCuTru", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
