// <auto-generated />
using System;
using HeThongChungCu.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeThongChungCu.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407031703_AddBangGiaLoaiCanHo")]
    partial class AddBangGiaLoaiCanHo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.BangGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DichVuId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiDinhGiaId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("TenBangGia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DichVuId");

                    b.ToTable("BangGia", (string)null);

                    b.HasDiscriminator<int>("LoaiDinhGiaId");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.CanHo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiCanHoId")
                        .HasColumnType("int");

                    b.Property<string>("MaCanHo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("TangId")
                        .HasColumnType("int");

                    b.Property<string>("TenCanHo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TinhTrangCanHoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaCanHo")
                        .IsUnique();

                    b.HasIndex("TangId");

                    b.ToTable("CanHo", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.ChiSoTieuThu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CanHoId")
                        .HasColumnType("int");

                    b.Property<decimal>("ChiSoCu")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ChiSoMoi")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DichVuId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("NgayChot")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DichVuId");

                    b.HasIndex("CanHoId", "DichVuId", "Thang", "Nam")
                        .IsUnique();

                    b.ToTable("ChiSoTieuThu", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.ChiTietGiaKhungGio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BangGiaId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KhungGioId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BangGiaId");

                    b.HasIndex("KhungGioId");

                    b.ToTable("ChiTietGiaKhungGio", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.ChiTietGiaLoaiCanHo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BangGiaId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LoaiCanHoId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BangGiaId");

                    b.ToTable("ChiTietGiaLoaiCanHo", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.ChiTietGiaLuyTien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BangGiaId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("DenMuc")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("TuMuc")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BangGiaId");

                    b.ToTable("ChiTietGiaLuyTien", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.DangKyDichVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CanHoId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DichVuId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiDangKyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CanHoId");

                    b.HasIndex("DichVuId");

                    b.ToTable("DangKyDichVu", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.DichVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IconId")
                        .HasColumnType("int");

                    b.Property<bool>("IsBatBuoc")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiDichVuId")
                        .HasColumnType("int");

                    b.Property<string>("MaDichVu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThaiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IconId");

                    b.ToTable("DichVu", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.DoiTac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaSoThue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("NguoiDaiDien")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoGiayPhepKD")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenCongTy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenDoiTac")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DoiTac", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.HoaDonDoiTac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("FileHoaDonId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HopDongDoiTacId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("NgayGhiNhan")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiThanhToanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FileHoaDonId");

                    b.HasIndex("HopDongDoiTacId");

                    b.ToTable("HoaDonDoiTac", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.HopDongDoiTac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DichVuId")
                        .HasColumnType("int");

                    b.Property<int>("DoiTacId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("NgayHetHan")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("NgayKy")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SoHopDong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThaiHopDongId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DichVuId");

                    b.HasIndex("DoiTacId");

                    b.ToTable("HopDongDoiTac", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.KhungGioDichVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DichVuId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int?>("NgayTrongTuan")
                        .HasColumnType("int");

                    b.Property<string>("TenKhungGio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DichVuId");

                    b.ToTable("KhungGioDichVu", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CCCD")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("GioiTinhId")
                        .HasColumnType("int");

                    b.Property<string>("Ho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("NgaySinh")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CCCD")
                        .IsUnique()
                        .HasFilter("[CCCD] IS NOT NULL");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.NhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiNhanVienId")
                        .HasColumnType("int");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("NgayNghiLam")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("NgayVaoLam")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiNhanVienId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaNhanVien")
                        .IsUnique();

                    b.HasIndex("NguoiDungId");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.PhanBoThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ThongBaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("ThongBaoId");

                    b.HasIndex("NguoiDungId", "IsRead");

                    b.ToTable("PhanBoThongBao", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.PhanQuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("TaiKhoanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("PhanQuyen", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.PhuongTien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BienSo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CanHoId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiPhuongTienId")
                        .HasColumnType("int");

                    b.Property<string>("MauXe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("TenPhuongTien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThaiPhuongTienId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BienSo")
                        .IsUnique();

                    b.HasIndex("CanHoId");

                    b.ToTable("PhuongTien", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.QuanHeCuTru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CanHoId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiQuanHeCuTruId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiCuTruId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("CanHoId", "NguoiDungId")
                        .IsUnique()
                        .HasFilter("[TrangThaiCuTruId] = 1");

                    b.ToTable("QuanHeCuTru", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnhDaiDienId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AnhDaiDienId");

                    b.HasIndex("NguoiDungId")
                        .IsUnique()
                        .HasFilter("[NguoiDungId] IS NOT NULL");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.TaiLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiGiayToId")
                        .HasColumnType("int");

                    b.Property<string>("LoaiTaiLieu")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("NgayPhatHanh")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SoGiayTo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TaiLieu", (string)null);

                    b.HasDiscriminator<string>("LoaiTaiLieu").HasValue("TaiLieu");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.Tang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiTangId")
                        .HasColumnType("int");

                    b.Property<string>("MaTang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("TenTang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ToaNhaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ToaNhaId", "MaTang")
                        .IsUnique();

                    b.ToTable("Tang", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.TepTaiLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LoaiTepTaiLieu")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TepTaiLieu", (string)null);

                    b.HasDiscriminator<string>("LoaiTepTaiLieu").HasValue("TepTaiLieu");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.ThePhuongTien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaThe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("PhuongTienId")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaThe")
                        .IsUnique();

                    b.HasIndex("PhuongTienId");

                    b.ToTable("ThePhuongTien", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiThongBao")
                        .HasColumnType("int");

                    b.Property<string>("Metadata")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.ToaNha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaToaNha")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("TenToaNha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThaiToaNhaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaToaNha")
                        .IsUnique();

                    b.ToTable("ToaNha", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.Tokens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ExpiresDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<int?>("ReasonRevoked")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TaiKhoanId")
                        .HasColumnType("int");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TokenType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("Token", (string)null);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.YeuCau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CanHoId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiYeuCauCuDan")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int>("LoaiYeuCauId")
                        .HasColumnType("int");

                    b.Property<string>("LyDo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("NgayXuLy")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("NguoiXuLyId")
                        .HasColumnType("int");

                    b.Property<int?>("NhanVienThucHienId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TrangThaiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CanHoId");

                    b.ToTable("YeuCau", (string)null);

                    b.HasDiscriminator<string>("LoaiYeuCauCuDan").HasValue("YeuCau");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.BangGiaCoDinh", b =>
                {
                    b.HasBaseType("HeThongChungCu.Domain.Entities.BangGia");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.BangGiaKhungGio", b =>
                {
                    b.HasBaseType("HeThongChungCu.Domain.Entities.BangGia");

                    b.HasDiscriminator().HasValue(7);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.BangGiaLoaiCanHo", b =>
                {
                    b.HasBaseType("HeThongChungCu.Domain.Entities.BangGia");

                    b.HasDiscriminator().HasValue(6);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.BangGiaLuyTien", b =>
                {
                    b.HasBaseType("HeThongChungCu.Domain.Entities.BangGia");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.TaiLieuNguoiDung", b =>
                {
                    b.HasBaseType("HeThongChungCu.Domain.Entities.TaiLieu");

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("int");

                    b.HasIndex("NguoiDungId");

                    b.HasDiscriminator().HasValue("TaiLieuNguoiDung");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.YeuCauTaiLieuCuTru", b =>
                {
                    b.HasBaseType("HeThongChungCu.Domain.Entities.TaiLieu");

                    b.Property<int?>("TaiLieuCuTruId")
                        .HasColumnType("int");

                    b.Property<int>("YeuCauCuTruId")
                        .HasColumnType("int");

                    b.HasIndex("YeuCauCuTruId");

                    b.HasDiscriminator().HasValue("YeuCauTaiLieuCuTru");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.TepHopDongDoiTac", b =>
                {
                    b.HasBaseType("HeThongChungCu.Domain.Entities.TepTaiLieu");

                    b.Property<int>("HopDongDoiTacId")
                        .HasColumnType("int");

                    b.HasIndex("HopDongDoiTacId");

                    b.HasDiscriminator().HasValue("TepHopDongDoiTac");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.TepPhuongTien", b =>
                {
                    b.HasBaseType("HeThongChungCu.Domain.Entities.TepTaiLieu");

                    b.Property<int>("PhuongTienId")
                        .HasColumnType("int");

                    b.HasIndex("PhuongTienId");

                    b.HasDiscriminator().HasValue("TepPhuongTien");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.TepTaiLieuNguoiDung", b =>
                {
                    b.HasBaseType("HeThongChungCu.Domain.Entities.TepTaiLieu");

                    b.Property<int>("TaiLieuNguoiDungId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("TaiLieuId");

                    b.HasIndex("TaiLieuNguoiDungId");

                    b.HasDiscriminator().HasValue("TepTaiLieuNguoiDung");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.TepYeuCauPhuongTien", b =>
                {
                    b.HasBaseType("HeThongChungCu.Domain.Entities.TepTaiLieu");

                    b.Property<int>("YeuCauPhuongTienId")
                        .HasColumnType("int")
                        .HasColumnName("YeuCauId");

                    b.HasIndex("YeuCauPhuongTienId");

                    b.HasDiscriminator().HasValue("TepYeuCauPhuongTien");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.TepYeuCauTaiLieuCuTru", b =>
                {
                    b.HasBaseType("HeThongChungCu.Domain.Entities.TepTaiLieu");

                    b.Property<int>("YeuCauTaiLieuCuTruId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("TaiLieuId");

                    b.HasIndex("YeuCauTaiLieuCuTruId");

                    b.HasDiscriminator().HasValue("TepYeuCauTaiLieuCuTru");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.YeuCauCuTru", b =>
                {
                    b.HasBaseType("HeThongChungCu.Domain.Entities.YeuCau");

                    b.Property<string>("YeuCauCCCD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("YeuCauGioiTinhId")
                        .HasColumnType("int");

                    b.Property<string>("YeuCauHo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("YeuCauLoaiQuanHeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("YeuCauNgaySinh")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("YeuCauQuanHeCuTruId")
                        .HasColumnType("int");

                    b.Property<string>("YeuCauTen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasDiscriminator().HasValue("YeuCauCuTru");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.YeuCauPhuongTien", b =>
                {
                    b.HasBaseType("HeThongChungCu.Domain.Entities.YeuCau");

                    b.Property<string>("YeuCauBienSo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("YeuCauLoaiPhuongTienId")
                        .HasColumnType("int");

                    b.Property<string>("YeuCauMauXe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("YeuCauPhuongTienId")
                        .HasColumnType("int");

                    b.Property<string>("YeuCauTenPhuongTien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasDiscriminator().HasValue("YeuCauPhuongTien");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.BangGia", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.DichVu", "DichVu")
                        .WithMany("BangGias")
                        .HasForeignKey("DichVuId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("HeThongChungCu.Domain.ValueObjects.ThoiGianHieuLuc", "ThoiGian", b1 =>
                        {
                            b1.Property<int>("BangGiaId")
                                .HasColumnType("int");

                            b1.Property<DateTimeOffset>("NgayBatDau")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("NgayApDung");

                            b1.Property<DateTimeOffset?>("NgayKetThuc")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("NgayKetThuc");

                            b1.HasKey("BangGiaId");

                            b1.ToTable("BangGia");

                            b1.WithOwner()
                                .HasForeignKey("BangGiaId");
                        });

                    b.Navigation("DichVu");

                    b.Navigation("ThoiGian")
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.CanHo", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.Tang", null)
                        .WithMany()
                        .HasForeignKey("TangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("HeThongChungCu.Domain.ValueObjects.ThongSoCanHo", "ThongSo", b1 =>
                        {
                            b1.Property<int>("CanHoId")
                                .HasColumnType("int");

                            b1.Property<decimal>("DienTich")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("DienTich");

                            b1.Property<int>("SoPhongNgu")
                                .HasColumnType("int")
                                .HasColumnName("SoPhongNgu");

                            b1.Property<int>("SoPhongTam")
                                .HasColumnType("int")
                                .HasColumnName("SoPhongTam");

                            b1.HasKey("CanHoId");

                            b1.ToTable("CanHo");

                            b1.WithOwner()
                                .HasForeignKey("CanHoId");
                        });

                    b.Navigation("ThongSo")
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.ChiSoTieuThu", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.CanHo", null)
                        .WithMany()
                        .HasForeignKey("CanHoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeThongChungCu.Domain.Entities.DichVu", null)
                        .WithMany()
                        .HasForeignKey("DichVuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.ChiTietGiaKhungGio", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.BangGiaKhungGio", "BangGia")
                        .WithMany("ChiTietGias")
                        .HasForeignKey("BangGiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongChungCu.Domain.Entities.KhungGioDichVu", "KhungGio")
                        .WithMany()
                        .HasForeignKey("KhungGioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("HeThongChungCu.Domain.ValueObjects.GiaTien", "DonGia", b1 =>
                        {
                            b1.Property<int>("ChiTietGiaKhungGioId")
                                .HasColumnType("int");

                            b1.Property<decimal>("SoTien")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("DonGia");

                            b1.HasKey("ChiTietGiaKhungGioId");

                            b1.ToTable("ChiTietGiaKhungGio");

                            b1.WithOwner()
                                .HasForeignKey("ChiTietGiaKhungGioId");
                        });

                    b.Navigation("BangGia");

                    b.Navigation("DonGia")
                        .IsRequired();

                    b.Navigation("KhungGio");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.ChiTietGiaLoaiCanHo", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.BangGiaLoaiCanHo", "BangGia")
                        .WithMany("ChiTietGias")
                        .HasForeignKey("BangGiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("HeThongChungCu.Domain.ValueObjects.GiaTien", "DonGia", b1 =>
                        {
                            b1.Property<int>("ChiTietGiaLoaiCanHoId")
                                .HasColumnType("int");

                            b1.Property<decimal>("SoTien")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("DonGia");

                            b1.HasKey("ChiTietGiaLoaiCanHoId");

                            b1.ToTable("ChiTietGiaLoaiCanHo");

                            b1.WithOwner()
                                .HasForeignKey("ChiTietGiaLoaiCanHoId");
                        });

                    b.Navigation("BangGia");

                    b.Navigation("DonGia")
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.ChiTietGiaLuyTien", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.BangGiaLuyTien", "BangGia")
                        .WithMany("ChiTietGias")
                        .HasForeignKey("BangGiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("HeThongChungCu.Domain.ValueObjects.GiaTien", "DonGia", b1 =>
                        {
                            b1.Property<int>("ChiTietGiaLuyTienId")
                                .HasColumnType("int");

                            b1.Property<decimal>("SoTien")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("DonGia");

                            b1.HasKey("ChiTietGiaLuyTienId");

                            b1.ToTable("ChiTietGiaLuyTien");

                            b1.WithOwner()
                                .HasForeignKey("ChiTietGiaLuyTienId");
                        });

                    b.Navigation("BangGia");

                    b.Navigation("DonGia")
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.DangKyDichVu", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.CanHo", null)
                        .WithMany()
                        .HasForeignKey("CanHoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeThongChungCu.Domain.Entities.DichVu", null)
                        .WithMany()
                        .HasForeignKey("DichVuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("HeThongChungCu.Domain.ValueObjects.ThoiGianHieuLuc", "ThoiGian", b1 =>
                        {
                            b1.Property<int>("DangKyDichVuId")
                                .HasColumnType("int");

                            b1.Property<DateTimeOffset>("NgayBatDau")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("NgayBatDau");

                            b1.Property<DateTimeOffset?>("NgayKetThuc")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("NgayKetThuc");

                            b1.HasKey("DangKyDichVuId");

                            b1.ToTable("DangKyDichVu");

                            b1.WithOwner()
                                .HasForeignKey("DangKyDichVuId");
                        });

                    b.Navigation("ThoiGian")
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.DichVu", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.TepTaiLieu", "Icon")
                        .WithMany()
                        .HasForeignKey("IconId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Icon");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.DoiTac", b =>
                {
                    b.OwnsOne("HeThongChungCu.Domain.ValueObjects.DiaChi", "DiaChi", b1 =>
                        {
                            b1.Property<int>("DoiTacId")
                                .HasColumnType("int");

                            b1.Property<string>("FullAddress")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("DiaChi");

                            b1.Property<string>("PhuongXa")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("QuanHuyen")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SoNhaTenDuong")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TinhThanhPho")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("DoiTacId");

                            b1.ToTable("DoiTac");

                            b1.WithOwner()
                                .HasForeignKey("DoiTacId");
                        });

                    b.OwnsOne("HeThongChungCu.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("DoiTacId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Email");

                            b1.HasKey("DoiTacId");

                            b1.ToTable("DoiTac");

                            b1.WithOwner()
                                .HasForeignKey("DoiTacId");
                        });

                    b.OwnsOne("HeThongChungCu.Domain.ValueObjects.SoDienThoai", "SoDienThoai", b1 =>
                        {
                            b1.Property<int>("DoiTacId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("SoDienThoai");

                            b1.HasKey("DoiTacId");

                            b1.ToTable("DoiTac");

                            b1.WithOwner()
                                .HasForeignKey("DoiTacId");
                        });

                    b.Navigation("DiaChi")
                        .IsRequired();

                    b.Navigation("Email");

                    b.Navigation("SoDienThoai");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.HoaDonDoiTac", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.TepTaiLieu", "FileHoaDon")
                        .WithMany()
                        .HasForeignKey("FileHoaDonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HeThongChungCu.Domain.Entities.HopDongDoiTac", null)
                        .WithMany()
                        .HasForeignKey("HopDongDoiTacId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("HeThongChungCu.Domain.ValueObjects.GiaTien", "SoTien", b1 =>
                        {
                            b1.Property<int>("HoaDonDoiTacId")
                                .HasColumnType("int");

                            b1.Property<decimal>("SoTien")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("SoTien");

                            b1.HasKey("HoaDonDoiTacId");

                            b1.ToTable("HoaDonDoiTac");

                            b1.WithOwner()
                                .HasForeignKey("HoaDonDoiTacId");
                        });

                    b.Navigation("FileHoaDon");

                    b.Navigation("SoTien")
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.HopDongDoiTac", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.DichVu", null)
                        .WithMany()
                        .HasForeignKey("DichVuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeThongChungCu.Domain.Entities.DoiTac", "DoiTac")
                        .WithMany("HopDongs")
                        .HasForeignKey("DoiTacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("HeThongChungCu.Domain.ValueObjects.GiaTien", "GiaTriHopDong", b1 =>
                        {
                            b1.Property<int>("HopDongDoiTacId")
                                .HasColumnType("int");

                            b1.Property<decimal>("SoTien")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("GiaTriHopDong");

                            b1.HasKey("HopDongDoiTacId");

                            b1.ToTable("HopDongDoiTac");

                            b1.WithOwner()
                                .HasForeignKey("HopDongDoiTacId");
                        });

                    b.Navigation("DoiTac");

                    b.Navigation("GiaTriHopDong")
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.KhungGioDichVu", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.DichVu", "DichVu")
                        .WithMany("KhungGios")
                        .HasForeignKey("DichVuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.NguoiDung", b =>
                {
                    b.OwnsOne("HeThongChungCu.Domain.ValueObjects.DiaChi", "DiaChi", b1 =>
                        {
                            b1.Property<int>("NguoiDungId")
                                .HasColumnType("int");

                            b1.Property<string>("FullAddress")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DiaChi");

                            b1.Property<string>("PhuongXa")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("QuanHuyen")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SoNhaTenDuong")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TinhThanhPho")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("NguoiDungId");

                            b1.ToTable("NguoiDung");

                            b1.WithOwner()
                                .HasForeignKey("NguoiDungId");
                        });

                    b.OwnsOne("HeThongChungCu.Domain.ValueObjects.SoDienThoai", "SoDienThoai", b1 =>
                        {
                            b1.Property<int>("NguoiDungId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("SoDienThoai");

                            b1.HasKey("NguoiDungId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasFilter("[SoDienThoai] IS NOT NULL");

                            b1.ToTable("NguoiDung");

                            b1.WithOwner()
                                .HasForeignKey("NguoiDungId");
                        });

                    b.Navigation("DiaChi")
                        .IsRequired();

                    b.Navigation("SoDienThoai");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.NhanVien", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.PhanBoThongBao", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HeThongChungCu.Domain.Entities.ThongBao", null)
                        .WithMany("PhanBoThongBaos")
                        .HasForeignKey("ThongBaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.PhanQuyen", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany("PhanQuyens")
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.PhuongTien", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.CanHo", null)
                        .WithMany()
                        .HasForeignKey("CanHoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.QuanHeCuTru", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.CanHo", null)
                        .WithMany()
                        .HasForeignKey("CanHoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HeThongChungCu.Domain.Entities.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("HeThongChungCu.Domain.ValueObjects.ThoiGianHieuLuc", "ThoiGian", b1 =>
                        {
                            b1.Property<int>("QuanHeCuTruId")
                                .HasColumnType("int");

                            b1.Property<DateTimeOffset>("NgayBatDau")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("NgayBatDau");

                            b1.Property<DateTimeOffset?>("NgayKetThuc")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("NgayKetThuc");

                            b1.HasKey("QuanHeCuTruId");

                            b1.ToTable("QuanHeCuTru");

                            b1.WithOwner()
                                .HasForeignKey("QuanHeCuTruId");
                        });

                    b.Navigation("ThoiGian")
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.TaiKhoan", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.TepTaiLieu", "AnhDaiDien")
                        .WithMany()
                        .HasForeignKey("AnhDaiDienId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HeThongChungCu.Domain.Entities.NguoiDung", null)
                        .WithOne()
                        .HasForeignKey("HeThongChungCu.Domain.Entities.TaiKhoan", "NguoiDungId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("HeThongChungCu.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("TaiKhoanId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("Email");

                            b1.HasKey("TaiKhoanId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("TaiKhoan");

                            b1.WithOwner()
                                .HasForeignKey("TaiKhoanId");
                        });

                    b.Navigation("AnhDaiDien");

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.Tang", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.ToaNha", "ToaNha")
                        .WithMany("Tangs")
                        .HasForeignKey("ToaNhaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ToaNha");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.ThePhuongTien", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.PhuongTien", null)
                        .WithMany("ThePhuongTiens")
                        .HasForeignKey("PhuongTienId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("HeThongChungCu.Domain.ValueObjects.ThoiGianHieuLuc", "ThoiGian", b1 =>
                        {
                            b1.Property<int>("ThePhuongTienId")
                                .HasColumnType("int");

                            b1.Property<DateTimeOffset>("NgayBatDau")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("NgayBatDau");

                            b1.Property<DateTimeOffset?>("NgayKetThuc")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("NgayKetThuc");

                            b1.HasKey("ThePhuongTienId");

                            b1.ToTable("ThePhuongTien");

                            b1.WithOwner()
                                .HasForeignKey("ThePhuongTienId");
                        });

                    b.Navigation("ThoiGian")
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.ToaNha", b =>
                {
                    b.OwnsOne("HeThongChungCu.Domain.ValueObjects.DiaChi", "DiaChi", b1 =>
                        {
                            b1.Property<int>("ToaNhaId")
                                .HasColumnType("int");

                            b1.Property<string>("FullAddress")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("DiaChi");

                            b1.Property<string>("PhuongXa")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("QuanHuyen")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SoNhaTenDuong")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TinhThanhPho")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ToaNhaId");

                            b1.ToTable("ToaNha");

                            b1.WithOwner()
                                .HasForeignKey("ToaNhaId");
                        });

                    b.Navigation("DiaChi")
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.Tokens", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany("Tokens")
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.YeuCau", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.CanHo", null)
                        .WithMany()
                        .HasForeignKey("CanHoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.BangGiaCoDinh", b =>
                {
                    b.OwnsOne("HeThongChungCu.Domain.ValueObjects.GiaTien", "DonGia", b1 =>
                        {
                            b1.Property<int>("BangGiaCoDinhId")
                                .HasColumnType("int");

                            b1.Property<decimal>("SoTien")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("DonGia");

                            b1.HasKey("BangGiaCoDinhId");

                            b1.ToTable("BangGia");

                            b1.WithOwner()
                                .HasForeignKey("BangGiaCoDinhId");
                        });

                    b.Navigation("DonGia")
                        .IsRequired();
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.TaiLieuNguoiDung", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany("TaiLieu")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.YeuCauTaiLieuCuTru", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.YeuCauCuTru", "YeuCauCuTru")
                        .WithMany("YeuCauTaiLieuCuTrus")
                        .HasForeignKey("YeuCauCuTruId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("YeuCauCuTru");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.TepHopDongDoiTac", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.HopDongDoiTac", "HopDongDoiTac")
                        .WithMany("TepHopDongs")
                        .HasForeignKey("HopDongDoiTacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDongDoiTac");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.TepPhuongTien", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.PhuongTien", "PhuongTien")
                        .WithMany("HinhAnhPhuongTiens")
                        .HasForeignKey("PhuongTienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhuongTien");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.TepTaiLieuNguoiDung", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.TaiLieuNguoiDung", "TaiLieuNguoiDung")
                        .WithMany("Files")
                        .HasForeignKey("TaiLieuNguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiLieuNguoiDung");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.TepYeuCauPhuongTien", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.YeuCauPhuongTien", "YeuCauPhuongTien")
                        .WithMany("YeuCauHinhAnhPhuongTiens")
                        .HasForeignKey("YeuCauPhuongTienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YeuCauPhuongTien");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.TepYeuCauTaiLieuCuTru", b =>
                {
                    b.HasOne("HeThongChungCu.Domain.Entities.YeuCauTaiLieuCuTru", "YeuCauTaiLieuCuTru")
                        .WithMany("Files")
                        .HasForeignKey("YeuCauTaiLieuCuTruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YeuCauTaiLieuCuTru");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.YeuCauCuTru", b =>
                {
                    b.OwnsOne("HeThongChungCu.Domain.ValueObjects.DiaChi", "YeuCauDiaChi", b1 =>
                        {
                            b1.Property<int>("YeuCauCuTruId")
                                .HasColumnType("int");

                            b1.Property<string>("FullAddress")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("YeuCauDiaChi");

                            b1.Property<string>("PhuongXa")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("QuanHuyen")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SoNhaTenDuong")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TinhThanhPho")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("YeuCauCuTruId");

                            b1.ToTable("YeuCau");

                            b1.WithOwner()
                                .HasForeignKey("YeuCauCuTruId");
                        });

                    b.OwnsOne("HeThongChungCu.Domain.ValueObjects.SoDienThoai", "YeuCauSoDienThoai", b1 =>
                        {
                            b1.Property<int>("YeuCauCuTruId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("nvarchar(15)")
                                .HasColumnName("YeuCauSoDienThoai");

                            b1.HasKey("YeuCauCuTruId");

                            b1.ToTable("YeuCau");

                            b1.WithOwner()
                                .HasForeignKey("YeuCauCuTruId");
                        });

                    b.Navigation("YeuCauDiaChi")
                        .IsRequired();

                    b.Navigation("YeuCauSoDienThoai");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.DichVu", b =>
                {
                    b.Navigation("BangGias");

                    b.Navigation("KhungGios");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.DoiTac", b =>
                {
                    b.Navigation("HopDongs");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.HopDongDoiTac", b =>
                {
                    b.Navigation("TepHopDongs");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.NguoiDung", b =>
                {
                    b.Navigation("TaiLieu");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.PhuongTien", b =>
                {
                    b.Navigation("HinhAnhPhuongTiens");

                    b.Navigation("ThePhuongTiens");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.TaiKhoan", b =>
                {
                    b.Navigation("PhanQuyens");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.ThongBao", b =>
                {
                    b.Navigation("PhanBoThongBaos");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.ToaNha", b =>
                {
                    b.Navigation("Tangs");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.BangGiaKhungGio", b =>
                {
                    b.Navigation("ChiTietGias");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.BangGiaLoaiCanHo", b =>
                {
                    b.Navigation("ChiTietGias");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.BangGiaLuyTien", b =>
                {
                    b.Navigation("ChiTietGias");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.TaiLieuNguoiDung", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.YeuCauTaiLieuCuTru", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.YeuCauCuTru", b =>
                {
                    b.Navigation("YeuCauTaiLieuCuTrus");
                });

            modelBuilder.Entity("HeThongChungCu.Domain.Entities.YeuCauPhuongTien", b =>
                {
                    b.Navigation("YeuCauHinhAnhPhuongTiens");
                });
#pragma warning restore 612, 618
        }
    }
}
